const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../root/www/luci-static/resources/view/zbox-device-limit/settings.js'), 'utf8');
const start = source.indexOf('function deviceName(');
const end = source.indexOf('\nfunction macValid(', start);
const name = new Function(source.slice(start, end) + '\nreturn deviceName;')();
const mac = '02:11:22:33:44:55';
const hosts = [{mac: mac.toUpperCase(), name: '静态租约 Example Device', ip: '192.0.2.10'}];
const leases = [{mac, name: '设备上报名称'}];
assert.equal(name(mac, '', leases, hosts), '静态租约 Example Device');
assert.equal(name(mac, '旧名称', leases, hosts), '静态租约 Example Device');
assert.equal(name(mac, '', [], hosts), '静态租约 Example Device');
assert.equal(name(mac, '', leases, []), '设备上报名称');
assert.equal(name(mac, '手动名称', leases, []), '手动名称');
assert.equal(name(mac, '', [], []), '');
hosts[0].name = '新的静态租约名';
assert.equal(name(mac, '', leases, hosts), '新的静态租约名');
console.log('PASS: static DHCP names, offline hosts, updated names, fallback and MAC case');
